language: python
python:
  - "3.4"
# command to install dependencies
install: 
- "pip install -U pip"
- "pip install -U pandas scikit-learn numpy matplotlib gensim geopandas spacy nltk mglearn nbconvert jupyter_client ipykernel"
# command to run tests
script: travis_wait 40 jupyter-nbconvert --execute hw4_starter_notebook.ipynb --ExecutePreprocessor.timeout=None
